### PR TITLE
added express boilerplate

### PR DESCRIPTION
**Pull request by Afraz0Khan**
**Description**

Express and Node.js (ts) server development

**Required Items**

- [ ] Title matches [../CONTRIBUTING.md](contributing guidelines)
- [ ] Linked Issue: #89 
- [ ] Code Reviewed
- [ ] Manually tested
- Style
  - [ ] No Lint Errors
  - [ ] Quality Comments
- Tests
  - [ ] Unit Tests Added
  - [ ] CI/CD passes
- UI
  - [ ] Picture of before/after UI (if applicable)

### CODE REVIEW

**Comment by Afraz0Khan** [comment]
Updated `package.json`. 
Ts-node not working for server entry file to start. Output: 
```
afrazkhan@Afrazs-MacBook-Pro DishZero % npx ts-node server.ts
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './server.ts'
Require stack:
- /Users/afrazkhan/Desktop/Codes/DishZero/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (/Users/afrazkhan/Desktop/Codes/DishZero/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/Users/afrazkhan/Desktop/Codes/DishZero/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/Users/afrazkhan/Desktop/Codes/DishZero/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/Users/afrazkhan/Desktop/Codes/DishZero/node_modules/ts-node/dist/bin.js:47:30)
    at main (/Users/afrazkhan/Desktop/Codes/DishZero/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/afrazkhan/Desktop/Codes/DishZero/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/afrazkhan/Desktop/Codes/DishZero/imaginaryUncacheableRequireResolveScript'
  ]
}

Node.js v17.6.0
```

**Comment by MacMalainey** [comment]
Would it be better to serve the main site through the custom backend? Or have a different project all together?

**Comment by Afraz0Khan** [comment]
Do you mean to create a separate folder for the server?

**Comment by MacMalainey** [comment]
Yes, I know there is a way to run custom targets using node, but I am not sure how to do that (would have to do research and play around).

Not sure if it is worth the time though?

**Comment by Afraz0Khan** [comment]
Yeah I'm also not sure of the time constraint here. I think it is better to complete the server as well as the backend in the same folder for now considering the repository would change entirely if we try to do otherwise.

**Comment by MacMalainey** [comment]
I mean different repository for the admin site + custom backend that is separate from the main site

**Comment by Afraz0Khan** [comment]
How about assigning roles to users (admin/common user) and directing routes accordingly in the same repo?

**Comment by MacMalainey** [comment]
We already assign roles to common users, the idea was though that any admin related functionality wouldn't be accessible at all from the original site (try and keep the admin code as far away from your average user as possible).

Additionally the admin site is to be designed as "desktop first" - so CSS styling might be a bit different for what would be common elements

**Pull request closed without merging**
